### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by davidgcorr-dev** [aspromatis/polygon_api#1]
mate your requirements file is corrupted, please clean it up and push, it has references to your filesystem 
Thanks for your work!

backcall==0.2.0
certifi==2020.6.20
chardet==3.0.4
cycler==0.10.0
decorator==4.4.2
idna==2.10
ipykernel
ipython
ipython-genutils==0.2.0
jedi
kiwisolver==1.2.0
matplotlib==3.3.2
numpy==1.19.2
pandas==1.1.3
parso==0.7.0
pexpect
pickleshare
Pillow==8.0.0
prompt-toolkit
ptyprocess==0.6.0
Pygments
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.1
pyzmq==19.0.2
requests==2.24.0
six==1.15.0
tornado==6.0.4
traitlets
urllib3==1.25.10
wcwidth

**Comment by A7DC** [comment]
thank you bud

**Comment by A7DC** [comment]
Still an issue in master?
